Table Empresas [headercolor: #175e7a] {
	empresa_id integer [ pk, increment, not null, unique ]
	nome_empresa varchar(150) [ not null ]
	tipo_empresa_id integer [ not null ]
	telefone_comercial varchar(20)
	endereco varchar(150)
	cidade varchar(100)
	estado_id integer [ not null ]
	cep varchar(9)
	website text
	observacoes text
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Table Tipos_Empresas [headercolor: #175e7a] {
	tipo_empresa_id integer [ pk, increment, not null, unique ]
	nome_tipo_empresa varchar(100) [ not null ]
}

Table Estados [headercolor: #175e7a] {
	estado_id integer [ pk, increment, not null, unique ]
	nome_estado varchar(100) [ not null ]
	sigla_estado char(2) [ not null ]
}

Table Produtos [headercolor: #175e7a] {
	produto_id integer [ pk, increment, not null, unique ]
	codigo_produto varchar(50)
	nome_produto varchar(150) [ not null ]
	descricao_produto text
	custo_unitario_padrao numeric(12,2)
	preco_unitario numeric(12,2)
	nivel_reposicao integer
	nivel_estoque_desejado integer
	quantidade_por_unidade varchar(50)
	descontinuado boolean [ not null ]
	quantidade_minima_reposicao integer
	categoria_produto_id integer [ not null ]
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Table Categorias_Produtos [headercolor: #175e7a] {
	categoria_produto_id integer [ pk, increment, not null, unique ]
	nome_categoria varchar(100) [ not null ]
}

Table Fornecedores_Produtos [headercolor: #175e7a] {
	fornecedor_produto_id integer [ pk, increment, not null, unique ]
	fornecedor_id integer [ not null ]
	produto_id integer [ not null ]
	codigo_fornecedor varchar(50)
	preco_compra numeric(12,2)
	quantidade_minima_pedido integer
	prazo_entrega_dias integer
	fornecedor_padrao boolean [ not null ]
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Table Pedidos_Compra [headercolor: #175e7a] {
	pedido_compra_id integer [ pk, increment, not null, unique ]
	fornecedor_id integer [ not null ]
	enviado_por integer
	data_envio timestamp
	aprovado_por integer
	data_aprovacao timestamp
	status_pedido_compra_id integer [ not null ]
	data_recebimento timestamp
	taxa_entrega numeric(12,2)
	valor_impostos numeric(12,2)
	data_pagamento timestamp
	valor_pagamento numeric(12,2)
	metodo_pagamento varchar(50)
	observacoes text
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Table Itens_Pedido_Compra [headercolor: #175e7a] {
	item_pedido_compra_id integer [ pk, increment, not null, unique ]
	pedido_compra_id integer [ not null ]
	produto_id integer [ not null ]
	quantidade numeric(10,2) [ not null ]
	custo_unitario numeric(12,2) [ not null ]
	data_recebimento timestamp
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Table Status_Pedido_Compra [headercolor: #175e7a] {
	status_pedido_compra_id integer [ pk, increment, not null, unique ]
	status varchar(50) [ not null ]
}

Table Pedidos [headercolor: #175e7a] {
	pedido_id integer [ pk, increment, not null, unique ]
	funcionario_id integer [ not null ]
	empresa_id integer [ not null ]
	data_pedido timestamp
	data_fatura timestamp
	data_envio timestamp
	taxa_entrega numeric(12,2)
	metodo_pagamento varchar(50)
	data_pagamento timestamp
	observacoes text
	status_pedido_id integer [ not null ]
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Table Itens_Pedido [headercolor: #175e7a] {
	item_pedido_id integer [ pk, increment, not null, unique ]
	pedido_id integer [ not null ]
	produto_id integer [ not null ]
	quantidade numeric(10,2) [ not null ]
	preco_unitario numeric(12,2) [ not null ]
	desconto numeric(5,2) [ not null ]
	status_pedido_id integer [ not null ]
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Table Status_Pedido [headercolor: #175e7a] {
	status_pedido_id integer [ pk, increment, not null, unique ]
	status varchar(50) [ not null ]
}

Table Inventario_Estoque [headercolor: #175e7a] {
	inventario_estoque_id integer [ pk, increment, not null, unique ]
	data_inventario timestamp [ not null ]
	produto_id integer [ not null ]
	quantidade_estoque numeric(10,2) [ not null ]
	quantidade_esperada numeric(10,2) [ not null ]
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Table Funcionarios [headercolor: #175e7a] {
	funcionario_id integer [ pk, increment, not null, unique ]
	sobrenome varchar(100) [ not null ]
	nome varchar(100) [ not null ]
	email varchar(150)
	cargo varchar(100)
	telefone_principal varchar(20)
	telefone_secundario varchar(20)
	titulo varchar(100)
	observacoes text
	anexos bytea
	usuario varchar(100)
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Table Privilegios [headercolor: #175e7a] {
	privilegio_id integer [ pk, increment, not null, unique ]
	nome_privilegio varchar(100) [ not null ]
}

Table Privilegios_Funcionarios [headercolor: #175e7a] {
	privilegio_funcionario_id integer [ pk, increment, not null, unique ]
	funcionario_id integer [ not null ]
	privilegio_id integer [ not null ]
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Ref fk_Empresas_tipo_empresa_id_Tipos_Empresas {
	Empresas.tipo_empresa_id > Tipos_Empresas.tipo_empresa_id [ delete: no action, update: no action ]
}

Ref fk_Empresas_estado_id_Estados {
	Empresas.estado_id > Estados.estado_id [ delete: no action, update: no action ]
}

Ref fk_Produtos_categoria_produto_id_Categorias_Produtos {
	Produtos.categoria_produto_id > Categorias_Produtos.categoria_produto_id [ delete: no action, update: no action ]
}

Ref fk_Fornecedores_Produtos_produto_id_Produtos {
	Fornecedores_Produtos.produto_id > Produtos.produto_id [ delete: no action, update: no action ]
}

Ref fk_Fornecedores_Produtos_fornecedor_id_Empresas {
	Fornecedores_Produtos.fornecedor_id > Empresas.empresa_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_Compra_fornecedor_id_Empresas {
	Pedidos_Compra.fornecedor_id > Empresas.empresa_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_Compra_status_pedido_compra_id_Status_Pedido_Compra {
	Pedidos_Compra.status_pedido_compra_id > Status_Pedido_Compra.status_pedido_compra_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_Compra_enviado_por_Funcionarios {
	Pedidos_Compra.enviado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_Compra_aprovado_por_Funcionarios {
	Pedidos_Compra.aprovado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_Compra_cadastrado_por_Funcionarios {
	Pedidos_Compra.cadastrado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_Compra_alterado_por_Funcionarios {
	Pedidos_Compra.alterado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_Compra_pedido_compra_id_Pedidos_Compra {
	Itens_Pedido_Compra.pedido_compra_id > Pedidos_Compra.pedido_compra_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_Compra_produto_id_Produtos {
	Itens_Pedido_Compra.produto_id > Produtos.produto_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_Compra_cadastrado_por_Funcionarios {
	Itens_Pedido_Compra.cadastrado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_Compra_alterado_por_Funcionarios {
	Itens_Pedido_Compra.alterado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_funcionario_id_Funcionarios {
	Pedidos.funcionario_id > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_empresa_id_Empresas {
	Pedidos.empresa_id > Empresas.empresa_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_status_pedido_id_Status_Pedido {
	Pedidos.status_pedido_id > Status_Pedido.status_pedido_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_cadastrado_por_Funcionarios {
	Pedidos.cadastrado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_alterado_por_Funcionarios {
	Pedidos.alterado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_pedido_id_Pedidos {
	Itens_Pedido.pedido_id > Pedidos.pedido_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_produto_id_Produtos {
	Itens_Pedido.produto_id > Produtos.produto_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_status_pedido_id_Status_Pedido {
	Itens_Pedido.status_pedido_id > Status_Pedido.status_pedido_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_cadastrado_por_Funcionarios {
	Itens_Pedido.cadastrado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_alterado_por_Funcionarios {
	Itens_Pedido.alterado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Inventario_Estoque_produto_id_Produtos {
	Inventario_Estoque.produto_id > Produtos.produto_id [ delete: no action, update: no action ]
}

Ref fk_Inventario_Estoque_cadastrado_por_Funcionarios {
	Inventario_Estoque.cadastrado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Inventario_Estoque_alterado_por_Funcionarios {
	Inventario_Estoque.alterado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Produtos_cadastrado_por_Funcionarios {
	Produtos.cadastrado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Produtos_alterado_por_Funcionarios {
	Produtos.alterado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Fornecedores_Produtos_cadastrado_por_Funcionarios {
	Fornecedores_Produtos.cadastrado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Fornecedores_Produtos_alterado_por_Funcionarios {
	Fornecedores_Produtos.alterado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Empresas_cadastrado_por_Funcionarios {
	Empresas.cadastrado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Empresas_alterado_por_Funcionarios {
	Empresas.alterado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Privilegios_Funcionarios_funcionario_id_Funcionarios {
	Privilegios_Funcionarios.funcionario_id > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Privilegios_Funcionarios_privilegio_id_Privilegios {
	Privilegios_Funcionarios.privilegio_id > Privilegios.privilegio_id [ delete: no action, update: no action ]
}

Ref fk_Funcionarios_cadastrado_por_Funcionarios {
	Funcionarios.cadastrado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Funcionarios_alterado_por_Funcionarios {
	Funcionarios.alterado_por > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}