Table Empresas [headercolor: #175e7a] {
	empresa_id integer [ pk, increment, not null, unique ]
	nome_empresa varchar(150) [ not null ]
	tipo_empresa varchar(100)
	telefone_comercial varchar(80)
	endereco varchar(150)
	cidade varchar(100)
	nome_estado varchar(100)
	sigla_estado char(2)
	cep integer
	website varchar(100)
	observacoes text
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Table Produtos [headercolor: #175e7a] {
	produto_id integer [ pk, increment, not null, unique ]
	codigo_produto varchar(255)
	nome_produto varchar(500) [ not null ]
	descricao_produto text
	custo_unitario_padrao float
	preco_unitario float
	nivel_reposicao integer
	nivel_estoque_desejado integer
	quantidade_por_unidade text
	descontinuado boolean [ not null ]
	quantidade_minima_reposicao integer
	nome_categoria varchar(100)
	nome_fornecedor varchar(150)
	codigo_fornecedor varchar(50)
	preco_compra numeric(12,2)
	quantidade_minima_pedido integer
	prazo_entrega_dias integer
	fornecedor_padrao boolean [ not null ]
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Table Inventario_Estoque [headercolor: #175e7a] {
	inventario_estoque_id integer [ pk, increment, not null, unique ]
	data_inventario timestamp [ not null ]
	produto_id integer [ not null ]
	quantidade_estoque numeric(10,2) [ not null ]
	quantidade_esperada numeric(10,2) [ not null ]
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
	codigo_produto varchar(255)
	nome_produto varchar(500)
}

Table Pedidos [headercolor: #175e7a] {
	pedido_id integer [ pk, increment, not null, unique ]
	funcionario_id integer [ not null ]
	empresa_id integer [ not null ]
	data_pedido timestamp
	data_fatura timestamp
	data_envio timestamp
	taxa_entrega float
	metodo_pagamento varchar(200)
	data_pagamento timestamp
	observacoes text
	status varchar(50)
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
	nome_empresa varchar(500)
	cidade_empresa varchar(300)
	telefone_empresa varchar(80)
	nome_funcionario varchar(100)
}

Table Itens_Pedido [headercolor: #175e7a] {
	item_pedido_id integer [ pk, increment, not null, unique ]
	pedido_id integer [ not null ]
	produto_id integer [ not null ]
	quantidade integer [ not null ]
	preco_unitario float [ not null ]
	desconto numeric(5,2) [ not null ]
	status_pedido_id integer [ not null ]
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
	codigo_produto varchar(255)
	nome_produto varchar(500)
}

Table Pedidos_Compra [headercolor: #175e7a] {
	pedido_compra_id integer [ pk, increment, not null, unique ]
	fornecedor_id integer [ not null ]
	enviado_por integer
	data_envio timestamp
	aprovado_por integer
	data_aprovacao timestamp
	status varchar(50)
	data_recebimento timestamp
	taxa_entrega numeric(12,2)
	valor_impostos float
	data_pagamento timestamp
	valor_pagamento float
	metodo_pagamento varchar(200)
	observacoes text
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
	nome_fornecedor varchar(500)
	telefone_fornecedor varchar(80)
}

Table Itens_Pedido_Compra [headercolor: #175e7a] {
	item_pedido_compra_id integer [ pk, increment, not null, unique ]
	pedido_compra_id integer [ not null ]
	produto_id integer [ not null ]
	quantidade integer [ not null ]
	custo_unitario float [ not null ]
	data_recebimento timestamp
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
	codigo_produto varchar(255)
	nome_produto varchar(500)
}

Table Funcionarios [headercolor: #175e7a] {
	funcionario_id integer [ pk, increment, not null, unique ]
	sobrenome varchar(100) [ not null ]
	nome varchar(100) [ not null ]
	email text
	cargo varchar(100)
	telefone_principal bigint
	telefone_secundario bigint
	titulo varchar(100)
	privilegio varchar(100)
	observacoes text
	anexos bytea
	usuario varchar(100)
	cadastrado_por integer
	data_cadastro timestamp
	alterado_por integer
	data_alteracao timestamp
}

Ref fk_Pedidos_empresa_id_Empresas {
	Pedidos.empresa_id > Empresas.empresa_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_funcionario_id_Funcionarios {
	Pedidos.funcionario_id > Funcionarios.funcionario_id [ delete: no action, update: no action ]
}

Ref fk_Pedidos_Compra_fornecedor_id_Empresas {
	Pedidos_Compra.fornecedor_id > Empresas.empresa_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_pedido_id_Pedidos {
	Itens_Pedido.pedido_id > Pedidos.pedido_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_produto_id_Produtos {
	Itens_Pedido.produto_id > Produtos.produto_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_Compra_pedido_compra_id_Pedidos_Compra {
	Itens_Pedido_Compra.pedido_compra_id > Pedidos_Compra.pedido_compra_id [ delete: no action, update: no action ]
}

Ref fk_Itens_Pedido_Compra_produto_id_Produtos {
	Itens_Pedido_Compra.produto_id > Produtos.produto_id [ delete: no action, update: no action ]
}

Ref fk_Inventario_Estoque_produto_id_Produtos {
	Inventario_Estoque.produto_id > Produtos.produto_id [ delete: no action, update: no action ]
}