CREATE TABLE IF NOT EXISTS "Empresas" (
	"empresa_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome_empresa" VARCHAR(150) NOT NULL,
	"tipo_empresa_id" INTEGER NOT NULL,
	"telefone_comercial" VARCHAR(20),
	"endereco" VARCHAR(150),
	"cidade" VARCHAR(100),
	"estado_id" INTEGER NOT NULL,
	"cep" VARCHAR(9),
	"website" TEXT,
	"observacoes" TEXT,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("empresa_id")
);




CREATE TABLE IF NOT EXISTS "Tipos_Empresas" (
	"tipo_empresa_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome_tipo_empresa" VARCHAR(100) NOT NULL,
	PRIMARY KEY("tipo_empresa_id")
);




CREATE TABLE IF NOT EXISTS "Estados" (
	"estado_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome_estado" VARCHAR(100) NOT NULL,
	"sigla_estado" CHAR(2) NOT NULL,
	PRIMARY KEY("estado_id")
);




CREATE TABLE IF NOT EXISTS "Produtos" (
	"produto_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"codigo_produto" VARCHAR(50),
	"nome_produto" VARCHAR(150) NOT NULL,
	"descricao_produto" TEXT,
	"custo_unitario_padrao" NUMERIC(12,2),
	"preco_unitario" NUMERIC(12,2),
	"nivel_reposicao" INTEGER,
	"nivel_estoque_desejado" INTEGER,
	"quantidade_por_unidade" VARCHAR(50),
	"descontinuado" BOOLEAN NOT NULL,
	"quantidade_minima_reposicao" INTEGER,
	"categoria_produto_id" INTEGER NOT NULL,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("produto_id")
);




CREATE TABLE IF NOT EXISTS "Categorias_Produtos" (
	"categoria_produto_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome_categoria" VARCHAR(100) NOT NULL,
	PRIMARY KEY("categoria_produto_id")
);




CREATE TABLE IF NOT EXISTS "Fornecedores_Produtos" (
	"fornecedor_produto_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fornecedor_id" INTEGER NOT NULL,
	"produto_id" INTEGER NOT NULL,
	"codigo_fornecedor" VARCHAR(50),
	"preco_compra" NUMERIC(12,2),
	"quantidade_minima_pedido" INTEGER,
	"prazo_entrega_dias" INTEGER,
	"fornecedor_padrao" BOOLEAN NOT NULL,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("fornecedor_produto_id")
);




CREATE TABLE IF NOT EXISTS "Pedidos_Compra" (
	"pedido_compra_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fornecedor_id" INTEGER NOT NULL,
	"enviado_por" INTEGER,
	"data_envio" TIMESTAMP,
	"aprovado_por" INTEGER,
	"data_aprovacao" TIMESTAMP,
	"status_pedido_compra_id" INTEGER NOT NULL,
	"data_recebimento" TIMESTAMP,
	"taxa_entrega" NUMERIC(12,2),
	"valor_impostos" NUMERIC(12,2),
	"data_pagamento" TIMESTAMP,
	"valor_pagamento" NUMERIC(12,2),
	"metodo_pagamento" VARCHAR(50),
	"observacoes" TEXT,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("pedido_compra_id")
);




CREATE TABLE IF NOT EXISTS "Itens_Pedido_Compra" (
	"item_pedido_compra_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"pedido_compra_id" INTEGER NOT NULL,
	"produto_id" INTEGER NOT NULL,
	"quantidade" NUMERIC(10,2) NOT NULL,
	"custo_unitario" NUMERIC(12,2) NOT NULL,
	"data_recebimento" TIMESTAMP,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("item_pedido_compra_id")
);




CREATE TABLE IF NOT EXISTS "Status_Pedido_Compra" (
	"status_pedido_compra_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"status" VARCHAR(50) NOT NULL,
	PRIMARY KEY("status_pedido_compra_id")
);




CREATE TABLE IF NOT EXISTS "Pedidos" (
	"pedido_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"funcionario_id" INTEGER NOT NULL,
	"empresa_id" INTEGER NOT NULL,
	"data_pedido" TIMESTAMP,
	"data_fatura" TIMESTAMP,
	"data_envio" TIMESTAMP,
	"taxa_entrega" NUMERIC(12,2),
	"metodo_pagamento" VARCHAR(50),
	"data_pagamento" TIMESTAMP,
	"observacoes" TEXT,
	"status_pedido_id" INTEGER NOT NULL,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("pedido_id")
);




CREATE TABLE IF NOT EXISTS "Itens_Pedido" (
	"item_pedido_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"pedido_id" INTEGER NOT NULL,
	"produto_id" INTEGER NOT NULL,
	"quantidade" NUMERIC(10,2) NOT NULL,
	"preco_unitario" NUMERIC(12,2) NOT NULL,
	"desconto" NUMERIC(5,2) NOT NULL,
	"status_pedido_id" INTEGER NOT NULL,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("item_pedido_id")
);




CREATE TABLE IF NOT EXISTS "Status_Pedido" (
	"status_pedido_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"status" VARCHAR(50) NOT NULL,
	PRIMARY KEY("status_pedido_id")
);




CREATE TABLE IF NOT EXISTS "Inventario_Estoque" (
	"inventario_estoque_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"data_inventario" TIMESTAMP NOT NULL,
	"produto_id" INTEGER NOT NULL,
	"quantidade_estoque" NUMERIC(10,2) NOT NULL,
	"quantidade_esperada" NUMERIC(10,2) NOT NULL,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("inventario_estoque_id")
);




CREATE TABLE IF NOT EXISTS "Funcionarios" (
	"funcionario_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"sobrenome" VARCHAR(100) NOT NULL,
	"nome" VARCHAR(100) NOT NULL,
	"email" VARCHAR(150),
	"cargo" VARCHAR(100),
	"telefone_principal" VARCHAR(20),
	"telefone_secundario" VARCHAR(20),
	"titulo" VARCHAR(100),
	"observacoes" TEXT,
	"anexos" BYTEA,
	"usuario" VARCHAR(100),
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("funcionario_id")
);




CREATE TABLE IF NOT EXISTS "Privilegios" (
	"privilegio_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome_privilegio" VARCHAR(100) NOT NULL,
	PRIMARY KEY("privilegio_id")
);




CREATE TABLE IF NOT EXISTS "Privilegios_Funcionarios" (
	"privilegio_funcionario_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"funcionario_id" INTEGER NOT NULL,
	"privilegio_id" INTEGER NOT NULL,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("privilegio_funcionario_id")
);



ALTER TABLE "Empresas"
ADD FOREIGN KEY("tipo_empresa_id") REFERENCES "Tipos_Empresas"("tipo_empresa_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Empresas"
ADD FOREIGN KEY("estado_id") REFERENCES "Estados"("estado_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Produtos"
ADD FOREIGN KEY("categoria_produto_id") REFERENCES "Categorias_Produtos"("categoria_produto_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Fornecedores_Produtos"
ADD FOREIGN KEY("produto_id") REFERENCES "Produtos"("produto_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Fornecedores_Produtos"
ADD FOREIGN KEY("fornecedor_id") REFERENCES "Empresas"("empresa_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos_Compra"
ADD FOREIGN KEY("fornecedor_id") REFERENCES "Empresas"("empresa_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos_Compra"
ADD FOREIGN KEY("status_pedido_compra_id") REFERENCES "Status_Pedido_Compra"("status_pedido_compra_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos_Compra"
ADD FOREIGN KEY("enviado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos_Compra"
ADD FOREIGN KEY("aprovado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos_Compra"
ADD FOREIGN KEY("cadastrado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos_Compra"
ADD FOREIGN KEY("alterado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido_Compra"
ADD FOREIGN KEY("pedido_compra_id") REFERENCES "Pedidos_Compra"("pedido_compra_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido_Compra"
ADD FOREIGN KEY("produto_id") REFERENCES "Produtos"("produto_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido_Compra"
ADD FOREIGN KEY("cadastrado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido_Compra"
ADD FOREIGN KEY("alterado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos"
ADD FOREIGN KEY("funcionario_id") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos"
ADD FOREIGN KEY("empresa_id") REFERENCES "Empresas"("empresa_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos"
ADD FOREIGN KEY("status_pedido_id") REFERENCES "Status_Pedido"("status_pedido_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos"
ADD FOREIGN KEY("cadastrado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos"
ADD FOREIGN KEY("alterado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido"
ADD FOREIGN KEY("pedido_id") REFERENCES "Pedidos"("pedido_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido"
ADD FOREIGN KEY("produto_id") REFERENCES "Produtos"("produto_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido"
ADD FOREIGN KEY("status_pedido_id") REFERENCES "Status_Pedido"("status_pedido_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido"
ADD FOREIGN KEY("cadastrado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido"
ADD FOREIGN KEY("alterado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Inventario_Estoque"
ADD FOREIGN KEY("produto_id") REFERENCES "Produtos"("produto_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Inventario_Estoque"
ADD FOREIGN KEY("cadastrado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Inventario_Estoque"
ADD FOREIGN KEY("alterado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Produtos"
ADD FOREIGN KEY("cadastrado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Produtos"
ADD FOREIGN KEY("alterado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Fornecedores_Produtos"
ADD FOREIGN KEY("cadastrado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Fornecedores_Produtos"
ADD FOREIGN KEY("alterado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Empresas"
ADD FOREIGN KEY("cadastrado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Empresas"
ADD FOREIGN KEY("alterado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Privilegios_Funcionarios"
ADD FOREIGN KEY("funcionario_id") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Privilegios_Funcionarios"
ADD FOREIGN KEY("privilegio_id") REFERENCES "Privilegios"("privilegio_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Funcionarios"
ADD FOREIGN KEY("cadastrado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Funcionarios"
ADD FOREIGN KEY("alterado_por") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;