CREATE TABLE IF NOT EXISTS "Empresas" (
	"empresa_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome_empresa" VARCHAR(150) NOT NULL,
	"tipo_empresa" VARCHAR(100),
	"telefone_comercial" VARCHAR(80),
	"endereco" VARCHAR(150),
	"cidade" VARCHAR(100),
	"nome_estado" VARCHAR(100),
	"sigla_estado" CHAR(2),
	"cep" INTEGER,
	"website" VARCHAR(100),
	"observacoes" TEXT,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("empresa_id")
);




CREATE TABLE IF NOT EXISTS "Produtos" (
	"produto_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"codigo_produto" VARCHAR(255),
	"nome_produto" VARCHAR(500) NOT NULL,
	"descricao_produto" TEXT,
	"custo_unitario_padrao" FLOAT,
	"preco_unitario" FLOAT,
	"nivel_reposicao" INTEGER,
	"nivel_estoque_desejado" INTEGER,
	"quantidade_por_unidade" TEXT,
	"descontinuado" BOOLEAN NOT NULL,
	"quantidade_minima_reposicao" INTEGER,
	"nome_categoria" VARCHAR(100),
	"nome_fornecedor" VARCHAR(150),
	"codigo_fornecedor" VARCHAR(50),
	"preco_compra" NUMERIC(12,2),
	"quantidade_minima_pedido" INTEGER,
	"prazo_entrega_dias" INTEGER,
	"fornecedor_padrao" BOOLEAN NOT NULL,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("produto_id")
);




CREATE TABLE IF NOT EXISTS "Inventario_Estoque" (
	"inventario_estoque_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"data_inventario" TIMESTAMP NOT NULL,
	"produto_id" INTEGER NOT NULL,
	"quantidade_estoque" NUMERIC(10,2) NOT NULL,
	"quantidade_esperada" NUMERIC(10,2) NOT NULL,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	"codigo_produto" VARCHAR(255),
	"nome_produto" VARCHAR(500),
	PRIMARY KEY("inventario_estoque_id")
);




CREATE TABLE IF NOT EXISTS "Pedidos" (
	"pedido_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"funcionario_id" INTEGER NOT NULL,
	"empresa_id" INTEGER NOT NULL,
	"data_pedido" TIMESTAMP,
	"data_fatura" TIMESTAMP,
	"data_envio" TIMESTAMP,
	"taxa_entrega" FLOAT,
	"metodo_pagamento" VARCHAR(200),
	"data_pagamento" TIMESTAMP,
	"observacoes" TEXT,
	"status" VARCHAR(50),
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	"nome_empresa" VARCHAR(500),
	"cidade_empresa" VARCHAR(300),
	"telefone_empresa" VARCHAR(80),
	"nome_funcionario" VARCHAR(100),
	PRIMARY KEY("pedido_id")
);




CREATE TABLE IF NOT EXISTS "Itens_Pedido" (
	"item_pedido_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"pedido_id" INTEGER NOT NULL,
	"produto_id" INTEGER NOT NULL,
	"quantidade" INTEGER NOT NULL,
	"preco_unitario" FLOAT NOT NULL,
	"desconto" NUMERIC(5,2) NOT NULL,
	"status_pedido_id" INTEGER NOT NULL,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	"codigo_produto" VARCHAR(255),
	"nome_produto" VARCHAR(500),
	PRIMARY KEY("item_pedido_id")
);




CREATE TABLE IF NOT EXISTS "Pedidos_Compra" (
	"pedido_compra_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fornecedor_id" INTEGER NOT NULL,
	"enviado_por" INTEGER,
	"data_envio" TIMESTAMP,
	"aprovado_por" INTEGER,
	"data_aprovacao" TIMESTAMP,
	"status" VARCHAR(50),
	"data_recebimento" TIMESTAMP,
	"taxa_entrega" NUMERIC(12,2),
	"valor_impostos" FLOAT,
	"data_pagamento" TIMESTAMP,
	"valor_pagamento" FLOAT,
	"metodo_pagamento" VARCHAR(200),
	"observacoes" TEXT,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	"nome_fornecedor" VARCHAR(500),
	"telefone_fornecedor" VARCHAR(80),
	PRIMARY KEY("pedido_compra_id")
);




CREATE TABLE IF NOT EXISTS "Itens_Pedido_Compra" (
	"item_pedido_compra_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"pedido_compra_id" INTEGER NOT NULL,
	"produto_id" INTEGER NOT NULL,
	"quantidade" INTEGER NOT NULL,
	"custo_unitario" FLOAT NOT NULL,
	"data_recebimento" TIMESTAMP,
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	"codigo_produto" VARCHAR(255),
	"nome_produto" VARCHAR(500),
	PRIMARY KEY("item_pedido_compra_id")
);




CREATE TABLE IF NOT EXISTS "Funcionarios" (
	"funcionario_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"sobrenome" VARCHAR(100) NOT NULL,
	"nome" VARCHAR(100) NOT NULL,
	"email" TEXT,
	"cargo" VARCHAR(100),
	"telefone_principal" BIGINT,
	"telefone_secundario" BIGINT,
	"titulo" VARCHAR(100),
	"privilegio" VARCHAR(100),
	"observacoes" TEXT,
	"anexos" BYTEA,
	"usuario" VARCHAR(100),
	"cadastrado_por" INTEGER,
	"data_cadastro" TIMESTAMP,
	"alterado_por" INTEGER,
	"data_alteracao" TIMESTAMP,
	PRIMARY KEY("funcionario_id")
);



ALTER TABLE "Pedidos"
ADD FOREIGN KEY("empresa_id") REFERENCES "Empresas"("empresa_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos"
ADD FOREIGN KEY("funcionario_id") REFERENCES "Funcionarios"("funcionario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pedidos_Compra"
ADD FOREIGN KEY("fornecedor_id") REFERENCES "Empresas"("empresa_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido"
ADD FOREIGN KEY("pedido_id") REFERENCES "Pedidos"("pedido_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido"
ADD FOREIGN KEY("produto_id") REFERENCES "Produtos"("produto_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido_Compra"
ADD FOREIGN KEY("pedido_compra_id") REFERENCES "Pedidos_Compra"("pedido_compra_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Itens_Pedido_Compra"
ADD FOREIGN KEY("produto_id") REFERENCES "Produtos"("produto_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Inventario_Estoque"
ADD FOREIGN KEY("produto_id") REFERENCES "Produtos"("produto_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;