INSERT INTO "Categorias_Produtos" (nome_categoria)
SELECT categoria
FROM (
VALUES

-- INFORMÁTICA
('Notebook Gamer'),
('Notebook Empresarial'),
('Notebook Ultrafino'),
('Notebook Entrada'),
('Notebook 2 em 1'),
('Desktop Gamer'),
('Desktop Empresarial'),
('Mini PC'),
('Servidor'),
('Monitor Gamer'),
('Monitor UltraWide'),
('Monitor LED'),
('Monitor 4K'),
('Mouse Gamer'),
('Mouse Sem Fio'),
('Mouse Office'),
('Teclado Mecânico'),
('Teclado Membrana'),
('Kit Teclado e Mouse'),
('Headset Gamer'),
('Webcam'),
('Microfone'),
('Caixa de Som para PC'),
('SSD SATA'),
('SSD NVMe'),
('HD Interno'),
('HD Externo'),
('Memória RAM'),
('Placa de Vídeo'),
('Placa Mãe'),
('Processador'),
('Cooler'),
('Fonte ATX'),
('Gabinete'),
('Roteador'),
('Switch'),
('Access Point'),
('Impressora'),
('Scanner'),
('Nobreak'),

-- SMARTPHONES
('Smartphone Android'),
('iPhone'),
('Smartphone Intermediário'),
('Smartphone Premium'),
('Celular Básico'),
('Capa'),
('Película'),
('Carregador'),
('Power Bank'),
('Fone Bluetooth'),
('Smartwatch'),
('Pulseira Inteligente'),
('Suporte Veicular'),
('Carregador Veicular'),
('Cabo USB'),

-- TVs
('TV LED'),
('TV OLED'),
('TV QLED'),
('TV Mini LED'),
('TV 32 Polegadas'),
('TV 43 Polegadas'),
('TV 50 Polegadas'),
('TV 55 Polegadas'),
('TV 65 Polegadas'),
('TV 75 Polegadas'),
('Projetor'),
('Suporte para TV'),

-- ÁUDIO
('Soundbar'),
('Home Theater'),
('Caixa Bluetooth'),
('Caixa Profissional'),
('Fone Intra Auricular'),
('Headphone'),
('Microfone Profissional'),
('Mesa de Som'),
('Amplificador'),
('Receiver'),

-- GAMES
('Console PlayStation'),
('Console Xbox'),
('Console Nintendo'),
('Controle'),
('Volante Gamer'),
('Cadeira Gamer'),
('Mesa Gamer'),
('Jogo PlayStation'),
('Jogo Xbox'),
('Jogo Nintendo'),

-- ELETRODOMÉSTICOS
('Geladeira Duplex'),
('Geladeira Side by Side'),
('Geladeira Frost Free'),
('Freezer Horizontal'),
('Freezer Vertical'),
('Fogão 4 Bocas'),
('Fogão 5 Bocas'),
('Cooktop'),
('Forno Elétrico'),
('Micro-ondas'),
('Coifa'),
('Depurador'),
('Lava Louças'),
('Lava e Seca'),
('Máquina de Lavar'),
('Secadora'),
('Tanquinho'),
('Purificador de Água'),
('Bebedouro'),
('Adega Climatizada'),

-- ELETROPORTÁTEIS
('Air Fryer'),
('Liquidificador'),
('Batedeira'),
('Cafeteira'),
('Espremedor'),
('Sanduicheira'),
('Grill'),
('Panela Elétrica'),
('Panela de Pressão Elétrica'),
('Aspirador de Pó'),
('Aspirador Robô'),
('Ventilador'),
('Climatizador'),
('Umidificador'),
('Ferro de Passar'),

-- AR CONDICIONADO
('Ar Condicionado Split'),
('Ar Condicionado Janela'),
('Ar Portátil'),
('Cortina de Ar'),
('Climatizador Industrial'),

-- MÓVEIS
('Sofá'),
('Rack'),
('Painel para TV'),
('Mesa de Jantar'),
('Cadeira'),
('Guarda-Roupa'),
('Cama Casal'),
('Cama Solteiro'),
('Colchão'),
('Escrivaninha'),
('Estante'),
('Mesa para Escritório'),
('Armário'),
('Criado Mudo'),
('Sapateira'),

-- ESCRITÓRIO
('Cadeira Office'),
('Mesa Office'),
('Arquivo'),
('Gaveteiro'),
('Notebook Office'),
('Monitor Office'),
('Calculadora'),
('Fragmentadora'),
('Telefone IP'),
('Telefone Sem Fio'),

-- FERRAMENTAS
('Furadeira'),
('Parafusadeira'),
('Martelete'),
('Serra Circular'),
('Serra Tico-Tico'),
('Esmerilhadeira'),
('Compressor'),
('Lavadora de Alta Pressão'),
('Kit Ferramentas'),
('Caixa de Ferramentas'),

-- AUTOMOTIVO
('Central Multimídia'),
('Som Automotivo'),
('Pneu'),
('Macaco Hidráulico'),
('Carregador de Bateria'),
('Capa para Banco'),
('Tapete Automotivo'),
('Aspirador Automotivo'),

-- ILUMINAÇÃO
('Lâmpada LED'),
('Luminária'),
('Refletor LED'),
('Painel LED'),
('Fita LED'),
('Abajur'),
('Lustre'),
('Spot LED'),

-- PAPELARIA
('Caderno'),
('Caneta'),
('Lápis'),
('Borracha'),
('Mochila'),
('Agenda'),
('Pasta'),
('Grampeador'),
('Calculadora Escolar'),
('Papel Sulfite'),

-- PET SHOP
('Ração Cães'),
('Ração Gatos'),
('Brinquedo Pet'),
('Coleira'),
('Cama Pet'),
('Comedouro'),
('Bebedouro Pet'),
('Caixa de Transporte'),

-- BRINQUEDOS
('Boneca'),
('Carrinho'),
('Blocos de Montar'),
('Quebra-Cabeça'),
('Jogo de Tabuleiro'),
('Patinete'),
('Bicicleta Infantil'),
('Pelúcia'),

-- CASA E DECORAÇÃO
('Cortina'),
('Tapete'),
('Espelho'),
('Quadro Decorativo'),
('Almofada'),
('Vaso Decorativo'),
('Relógio de Parede'),
('Organizador'),
('Cabide'),
('Lixeira')

) AS categorias(categoria);